### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by allentiak** [stevenhalim/cpbook-code#47]
Great tool and website!
Under which license is your code released? Apache 2.0?

**Comment by stevenhalim** [comment]
Hi Leandro,

Good idea to mention "license" in the repo.

I think I will use something like this
https://creativecommons.org/licenses/by/4.0/

all code there are (reasonably good, I hope) implementation of popular CS
textbook algorithms, so feel free to use them

Regards,

Steven Halim (Dr.)
Senior Lecturer
School of Computing, National University of Singapore
<http://www.comp.nus.edu.sg/~stevenha>
https://visualgo.net and https://cpbook.net

**Comment by allentiak** [comment]
Hi,

CC advises against using CC licenses for software https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software. They are good for other things, such as data.

If I understood well, your idea is allowing people to use your software for any purpose, as long as they mention you? If this is the case, I would advise you to use a non-copyleft, liberal license specially suited for software, such as Apache 2.0 https://www.gnu.org/licenses/license-list.html#apache2 

Please note that I am not a lawyer, and that this is not legal advise :-)

Best,
Leandro

**Comment by allentiak** [comment]
You could also use something like [BSD-3-clause](https://www.gnu.org/licenses/license-list.html#ModifiedBSD) or [UPL](https://www.gnu.org/licenses/license-list.html#UPL).

**Comment by allentiak** [comment]
BTW: I edited my first message.

**Comment by allentiak** [comment]
I meant: second comment :-)

**Comment by allentiak** [comment]
ping @stevenhalim ?

**Comment by stevenhalim** [comment]
Hi Leandro

I was away for family holiday in the past 4 days :O.

Ok thanks for telling me that CC license is not for software :O.
I think I will just pick UPL, very permissive license.

Regards,

Steven Halim (Dr.)
Senior Lecturer
School of Computing, National University of Singapore
<http://www.comp.nus.edu.sg/~stevenha>
https://visualgo.net and https://cpbook.net
