### ISSUE TITLE
Concise way to write the python io

### ISSUE THREAD

**Issue by git-hub-tig** [stevenhalim/cpbook-code#58]
Tks for your effort! Wonderful code!
Just a little improvement for python io.
```python
class SamInput(object):
    def __init__(self):
        self.inp = []
        for i in sys.stdin:
            i = i.replace("\n", "")
            j = list(i.split())
            self.inp.append(j)
```
canbe writed as:
```python
def __init__(self):
        self.inp=[line.split() for line in list(sys.stdin)] 
```
😅

**Comment by stevenhalim** [comment]
Hi git-hub-tig, thanks for the feedback.

I have just checked Python translation contributions from some of my (ex) students and decided that I will NOT use custom SamImput class and will just use Python (3) direct I/O methods most of the time to minimize SLOC, so I will do one pass over the repo and standardize this.

**Comment by git-hub-tig** [comment]
Cannot agree more, Python has got handy ways on I/O stream.
