### ISSUE TITLE
Bug in ch5/primes.cpp

### ISSUE THREAD

**Issue by seffendy** [stevenhalim/cpbook-code#62]
In `ch5/primes.cpp -- primeFactors(ll N)`:

```ll PF_idx = 0, PF = primes[PF_idx];
while (PF*PF <= N) {
  while (N%PF == 0) { N /= PF; factors.push_back(PF); }
  PF = primes[++PF_idx];
}
```
This code might crash due to index-out-of-bound in `PF = primes[++PF_idx]`. Consider the case when `PF_idx = primes.size()-1` (the last prime in `primes`), then when it goes to the problematic line, `PF_idx` becomes `primes.size()` which does not exist in `PF`.

This bug also happened in other functions as well, i.e., `numPF()`, `numDiffPF()`, `sumPF()`, `numDiv()`, `sumDiv()`, `EulerPhi()`.

**Comment by stevenhalim** [comment]
Eh this is not a bug, it is a feature, I will not change it, go to private discussion

**Comment by stevenhalim** [comment]
ok, not fully closed, let's discuss again

**Comment by stevenhalim** [comment]
this is done by now :)
