### ISSUE TITLE
LF and CR+LF

### ISSUE THREAD

**Issue by howsiwei** [stevenhalim/cpbook-code#68]
Currently some files use LF for line endings while some files use CR+LF for line endings. It would be good to convert all of them to LF.

**Comment by stevenhalim** [comment]
Should be mix of legacy code (written long ago -> Windows only) and recently (Unix).
I agree to convert them to Line Feed only (Unix).
If you spot them, please change.

**Comment by howsiwei** [comment]
Ok, I'll open a separate PR to convert them next week.
