### ISSUE TITLE
The code does not work properly

### ISSUE THREAD

**Issue by arsamigullin** [stevenhalim/cpbook-code#72]
Hello. Looks like this code does not work properly. 
https://github.com/stevenhalim/cpbook-code/blob/a49dd077cbaceb9e69b8630104dedc4645187065/ch6/string_alignment.py#L1
Consider this example
A = "horse"
B = "ros"

Actual result:
table[n][m] outputs 1 

Expected result:
table[n][m] should output 3

**Comment by stevenhalim** [comment]
Hi arsamigullin

Recheck again,

for, assuming match = +2 points and mismatch/insert/delete are all -1 point

A = "horse"
B = "ros"

becomes

A = "horse"
B = "ro_s_"
-1 +2 -1 +2 -1 = 1 point, not 3 points

so the code is correct.

Regards,

Steven Halim (Dr.)
Senior Lecturer
School of Computing, National University of Singapore
<http://www.comp.nus.edu.sg/~stevenha>
IOI 2020 (https://ioi2020.sg/) and 2021 (http://ioi2021.sg/) Deputy Director
https://visualgo.net and https://cpbook.net (CP4 is out)

**Comment by arsamigullin** [comment]
Thanks for your explanation. In Competitive Programming 4 (Book2) on page 329 it is said:
"The String Alignment (or Edit Distance) problem is defined as follows: Align two strings A with B with the maximum alignment score (or minimum number of edit operations)"

Thought that alignment score and number of edit operations have the same meaning. Looks like I was wrong

**Comment by stevenhalim** [comment]
the default is
Align two strings A with B with *the maximum alignment score *
with match given +2 and insert/mismatch/delete = -1 (these scores are
adjustable)

ok, I ignore this issue :)

Regards,

Steven Halim (Dr.)
Senior Lecturer
School of Computing, National University of Singapore
<http://www.comp.nus.edu.sg/~stevenha>
IOI 2020 (https://ioi2020.sg/) and 2021 (http://ioi2021.sg/) Deputy Director
https://visualgo.net and https://cpbook.net (CP4 is out)

**Comment by arsamigullin** [comment]
Yup, closed this ticket, thank you
